service: server

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  createDept:
    handler: ./api/department/createDept.createDept
    events:
      - httpApi:
          path: /createDept
          method: post
  displayDept:
    handler: ./api/department/displayDept.displayDept
    events:
      - httpApi:
          path: /displayDept
          method: get
  deleteDept:
    handler: ./api/department/deleteDept.deleteDept
    events:
      - httpApi:
          path: /deleteDept
          method: delete
  updateDept:
    handler: ./api/department/updateDept.updateDept
    events:
      - httpApi:
          path: /updateDept
          method: put
  createDivision:
    handler: ./api/division/createDivision.createDivision
    events:
      - httpApi:
          path: /createDivision
          method: post
  displayDivision:
    handler: ./api/division/displayDivision.displayDivision
    events:
      - httpApi:
          path: /displayDivision
          method: get
  displayDivisionById:
    handler: ./api/division/displayDivision.displayDivisionById
    events:
      - httpApi:
          path: /displayDivisionById/{_id}
          method: get
  deleteDivision:
    handler: ./api/division/deleteDivision.deleteDivision
    events:
      - httpApi:
          path: /deleteDivision
          method: delete
  updateDivision:
    handler: ./api/division/updateDivision.updateDivision
    events:
      - httpApi:
          path: /updateDivision
          method: put
  createDesignation:
    handler: ./api/designation/createDesignation.createDesignation
    events:
      - httpApi:
          path: /createDesignation
          method: post
  displayDesignation:
    handler: ./api/designation/displayDesignation.displayDesignation
    events:
      - httpApi:
          path: /displayDesignation
          method: get
  deleteDesignation:
    handler: ./api/designation/deleteDesignation.deleteDesignation
    events:
      - httpApi:
          path: /deleteDesignation
          method: delete
  updateDesignation:
    handler: ./api/designation/updateDesignation.updateDesignation
    events:
      - httpApi:
          path: /updateDesignation
          method: put
  createEmployee:
    handler: ./api/employee/createEmployee.createEmployee
    events:
      - httpApi:
          path: /createEmployee
          method: post
  deleteEmployee:
    handler: ./api/employee/deleteEmployee.deleteEmployee
    events:
      - httpApi:
          path: /deleteEmployee
          method: delete
  displayEmployee:
    handler: ./api/employee/displayEmployee.displayEmployee
    events:
      - httpApi:
          path: /displayEmployee
          method: get
  updateEmployee:
    handler: ./api/employee/updateEmployee.updateEmployee
    events:
      - httpApi:
          path: /updateEmployee
          method: put